// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdTLIUcThgX7kGO1rS0u1Fhnq6ht6XgvE',
    appId: '1:858092692119:web:40d288f9f7d27740973fd2',
    messagingSenderId: '858092692119',
    projectId: 'foodshareconnect-d9939',
    authDomain: 'foodshareconnect-d9939.firebaseapp.com',
    storageBucket: 'foodshareconnect-d9939.firebasestorage.app',
    measurementId: 'G-LY2ZYP18QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JDhLzZMUiUNXtNRv-9WG4ijJVzNa3rA',
    appId: '1:858092692119:android:bf70d8aa58f2b931973fd2',
    messagingSenderId: '858092692119',
    projectId: 'foodshareconnect-d9939',
    storageBucket: 'foodshareconnect-d9939.firebasestorage.app',
  );
}
